Added Polity5 and CShapes datasets and set up the package website
globalgov/qStates pull request #35
Opened 2021-07-27 17:30 UTC by BBieri

# Description

Please include a summary of the changes and which issues are fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change,
indicating whether this is a major (breaking), minor, or patch change.
Please also indicate if these are package changes, data changes, or both.  

## Package

- Fixed #26 by correcting state name detection in the `code_states()` function
- Fixed #30 by adapting qStates dataset preparation scripts to `{messydates}`
- Fixed #31 by creating qStates website

## Data

- Closes #1 by adding the Polity5 and the Polity5d datasets
- Closes #10  by integrating datasets on distances from CShapes
  - Integrated a vignette to showcase one potential workflow to create historical maps.

# Checklist:

- [x] PR form
  - [x] I have given this pull request an informative title
  - [x] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [x] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [x] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [x] Documentation
  - [x] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [x] Any longer functions are commented inline so that it is easier to debug in the future
  - [x] PR description above and the NEWS.md file are aligned
  - [x] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2021-07-28 15:38 UTC, BBieri commented
See [this issue on the `{sf}` repo](https://github.com/r-spatial/sf/issues/1733) for the cause of the failure of the `MacOS` workflow. We might have to wait a few days for them to release a new binary for x86 Mac. @henriquesposito @jhollway

2021-07-29 09:53 UTC, jhollway requested changes
I'll request the following changes, and then check the rest when these have been addressed.

2021-07-29 09:53 UTC, jhollway commented on tests/testthat/test_extract_cshapes.R
> +    expect_equal(class(test[["Beg"]]), "messydt")
This test line fails. It is instead 'Date' class.

2021-07-29 09:53 UTC, jhollway commented on data-raw/states/COW/prepare-COW.R
> +         End = qCreate::standardise_dates(endyear, endmonth, endday),
Some of these given end dates seem not to be padded with `0`s as expected. E.g. `1871-1-18` instead of `1871-01-18`

2021-07-29 09:53 UTC, jhollway commented on data-raw/states/COW/prepare-COW.R
> +         Beg = qCreate::standardise_dates(styear, stmonth, stday),
The `1816-1-1` should be `..1816-01-01`; both with 0 padding as well as indicating that all we know actually is that the dataset considers them states on 1st January 1816, but they may have been established (much) earlier.

2021-07-29 10:06 UTC, henriquesposito commented on tests/testthat/test_COW.R
> +test_that("Columns with dates are standardized", {
Remove all if calls from tests to avoid issues

2021-07-29 10:06 UTC, henriquesposito commented on tests/testthat/test_GW.R
> +  if (!is.null(states[["GW"]]$Beg)) {
Same

2021-07-29 10:06 UTC, henriquesposito commented on tests/testthat/test_ISD.R
> +  if (!is.null(states[["ISD"]]$Beg)) {
Same

2021-07-29 10:06 UTC, henriquesposito commented on tests/testthat/test_Polity5d.R
> +  if (!is.null(regimes[["Polity5d"]]$Label)) {
Remove if

2021-07-29 10:06 UTC, henriquesposito commented on tests/testthat/test_Polity5d.R
> +  if (!is.null(regimes[["Polity5d"]]$Beg)) {
Same

2021-07-29 10:06 UTC, henriquesposito commented on tests/testthat/test_extract_cshapes.R
> +  if (!is.null(test[["Beg"]])) {
same

2021-07-29 10:06 UTC, henriquesposito commented on vignettes/CShapesMaps.Rmd
> +Giving your readers a bird's eye view of your analysis can be a neat way to
A bit too convoluted of a sentence, could it be simplified?

2021-07-29 11:11 UTC, henriquesposito commented on tests/testthat/test_extract_cshapes.R
> +    expect_equal(class(test[["Beg"]]), "messydt")
I updated all the tests by removing, this was causing some warnings with devtools::test() when ran locally. Note that for tests to properly run locally with devtools::test() in qStates, you need to load the databases in the environment. This is why some of the tests appear to fail with tests but run without issues with devtools::check(). The same is true for qEnviron. In this specific case, once the database is loaded, the column is indeed "messydt" class.

2021-07-29 11:53 UTC, henriquesposito commented on data-raw/states/COW/prepare-COW.R
> +         End = qCreate::standardise_dates(endyear, endmonth, endday),
I will open an issue for this bug in messydates

2021-07-29 12:01 UTC, henriquesposito commented on data-raw/states/COW/prepare-COW.R
> +         Beg = qCreate::standardise_dates(styear, stmonth, stday),
I do understand the issue here and the expectations. However, the dates are set to a precise "start" date and I do not see a way in which we can programmatically implement this is messydates. I could add the ". ." manually to the column in the datasets, would you like me to do so? As for the padding I have opened an issue for this bug on messydates.

2021-07-29 12:04 UTC, henriquesposito commented on data-raw/states/ISD/prepare-ISD.R
> +              End = qCreate::standardise_dates(Finish),
See above.

2021-07-29 12:04 UTC, henriquesposito commented on data-raw/states/GW/prepare-GW.R
> +              Beg = qCreate::standardise_dates(Start),
Same as above.

2021-07-29 12:56 UTC, jhollway commented on data-raw/states/COW/prepare-COW.R
> +         Beg = qCreate::standardise_dates(styear, stmonth, stday),
Yes, this could only be decided manually. We could add a check that identifies a surprising proportion of observations that begin at the earliest observed date, but the decision is still a manual one. You could add some annotation functions to `{messydates}`, e.g.:

```r
eg ← on_or_before("1816-01-01")
eg == "..1816-01-01"

eg2 ← approximate_year("1816-01-01")
eg2 == "1816~-01-01"
```

2021-07-29 14:43 UTC, jhollway requested changes

2021-07-29 14:43 UTC, jhollway commented on data-raw/regimes/Polity5/prepare-Polity5.R
> +Polity5 <- readxl::read_excel("data-raw/regimes/Polity5/p5v2018.xls")
Why do we need both polity5 and polity5d?

2021-07-29 14:43 UTC, jhollway commented on vignettes/CShapesMaps.Rmd
> +and data about GDP in 1980.
Very good, but maybe we can then highlight how this is a historical map by pointing to e.g. West and East Germany in the text?

2021-07-29 14:43 UTC, jhollway commented on tests/testthat/test_extract_cshapes.R
> +  expect_equal(class(test[["Beg"]]), "messydt")
Still seems to be an error here?

2021-07-29 14:43 UTC, jhollway commented on R/code_states.R
> +}
Why do we need this? It seems just a wrapper. Our own code_states _should_ be broader anyway.

2021-07-29 14:43 UTC, jhollway commented on DESCRIPTION
>      pointblank
Is pointblank still a Depends for all qPackages, or just an Imports now?

2021-07-29 14:43 UTC, jhollway commented on .github/workflows/pushrelease.yml
> +          remotes::install_github("globalgov/qStates")
But isn't it qData that is the required additional package that isn't already downloaded as a dependency because it's not on CRAN? Moreover, why would you install from GitHub the package that you are currently trying to build?

2021-07-29 14:43 UTC, jhollway commented on NEWS.md
> +  * Added `import_distmatrix()` function to import CShapes distance matrixes
Maybe separate by database?

2021-07-29 14:43 UTC, jhollway commented on README.md
> +providers for their work assembling the data using the function below.
Great!

2021-07-30 07:59 UTC, henriquesposito commented on DESCRIPTION
>      pointblank
We still depend on pointblank for testing, the tests imported when setting up the package and when adding data require pointblank. At the same time, code factor does not like library() calls in scripts ...

2021-07-30 09:23 UTC, henriquesposito commented on data-raw/regimes/Polity5/prepare-Polity5.R
> +Polity5 <- readxl::read_excel("data-raw/regimes/Polity5/p5v2018.xls")
As I understand, the two Polity datasets have a different structure. Polity5 is year-country dataset while Polity5d is a "polity case" dataset (e.g. one observation per regime change). We do not necessarily need both, but depending on what is to be done it is nice to rely in one or the other. I would vote to leave both datasets in for now, once/if we add more cases to the regimes database later we can decide which version might make sense to exclude.

2021-07-30 09:47 UTC, henriquesposito commented on data-raw/states/COW/prepare-COW.R
> +         Beg = qCreate::standardise_dates(styear, stmonth, stday),
I added these manually to qStates datasets where requested. 

I have also opened an issue for this on messydates as I think this is an important aspect that we can provide guidelines and help for authors to deal with.

2021-07-30 10:23 UTC, henriquesposito commented on R/code_states.R
> +}
At the moment, we do not need this, so I commented out this function in the script. However, this functions codes states at different levels, as continents or supranational organizations for examples. I have the feeling that this functionality will be helpful for plotting and analysis later down the road,  and that it will be helpful to have some type of function like this. For that reason, I commented it out in the script for now instead of removing it.

2021-07-30 13:36 UTC, jhollway commented on R/code_states.R
> +}
Hmm, then `code_regions()` or so? I'll resolve this for now, but may be worth considering extensions.

2021-07-30 13:37 UTC, jhollway commented on data-raw/states/COW/prepare-COW.R
> +         Beg = qCreate::standardise_dates(styear, stmonth, stday),
Yes, this should be done too.

2021-07-30 13:45 UTC, jhollway requested changes

2021-07-30 13:45 UTC, jhollway commented on NEWS.md
> +* Added vignette for working with CShapes and maps
I think pkgdown likes it when package names are in `{packageName}` format, but best check

2021-07-30 13:45 UTC, jhollway commented on R/code_states.R
> +#' code_states(states)
Maybe also an example that highlights that it'll recognise country names in longer character strings (e.g. treaty titles)?

2021-07-30 13:45 UTC, jhollway commented on R/qStates-regimes.R
> +#' interim, bprec, post, change, d5, sf, regtrans.}
Great, I could imagine additional datasets to add here could include Freedom House Index, Vanhanen's Polyarchy index of democracy, etc.

2021-07-30 13:45 UTC, jhollway commented on data-raw/regimes/Polity5/prepare-Polity5.R
> +                     URL = "http://www.systemicpeace.org/inscrdata.html")
Both Polity5 and Polity5d appear in `qStates::regimes`?

2021-07-30 13:45 UTC, jhollway commented on data-raw/states/COW/prepare-COW.R
> +         End = qCreate::standardise_dates(endyear, endmonth, endday),
I still don't see the padding here. Are we just waiting on the messydates fix?

2021-07-30 13:57 UTC, henriquesposito commented on R/qStates-regimes.R
> +#' interim, bprec, post, change, d5, sf, regtrans.}
I will open and issue for this then

2021-08-16 11:52 UTC, merged